### ISSUE TITLE
Sale como "Hernani" pero es Donostia

### ISSUE THREAD

**Issue by numeroteca** [DataHippo/WebApi#14]
En el listado por ciudades San Sebastián - Donostia sale como "Hernani"

**Comment by numeroteca** [comment]
Me cuenta @Saigesp: "es porque se ha sacado consultando a Google, algún que otro error hay (y muchas regiones sin identificar). He creado una interfaz básica para poder editar nombre y datos básicos de cada región manualmente (con el tiempo serán más)". 
Hará falta usuario para poder corregir esos errores.

**Comment by Saigesp** [comment]
Si, está ya corregio
